# Generated by Django 6.0.5 on 2026-05-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='count_likes',
            field=models.IntegerField(default=0),
        ),
    ]
